refactor: ♻️ Changed parameter "style" to "Instructions"
LyzrCore/lyzr pull request #41
Opened 2024-04-18 12:43 UTC by praveenlyzr

## Description

**What**:   Changed parameter style to Instructions
**Why**:   To improve clarity for user
**How**:  I changed function parameter and internally changed the variable i used to refer to it.

## What type of PR is this?

- [ ] :gift: New feature (non-breaking change which adds functionality)
- [ ] :bug: Bug fix (non-breaking change which fixes an issue)
- [ ] :bomb: Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] :memo: Documentation update
- [x] :art: Refactor or style update
- [ ] :fire: Performance improvements
- [ ] :white_check_mark: Test
- [ ] :robot: Build
- [ ] :repeat: CI, review, release, devops, chore, etc.

## Added tests?

- [ ] :ballot_box_with_check: Yes
- [x] :negative_squared_cross_mark: No, and this is why:  Not really needed
- [ ] :question: No, because I need help.

## How can this be tested?

**Test A**
- Description: 
- Test Configuration: 
- Test Instructions: 
- Libraries: 
- Expected Result: 

## [optional] Are there any post-deployment tasks we need to perform?

## Checklist:

- [ ] :sunglasses: My code follows the style guidelines of this project.
- [ ] :ballot_box_with_check: I have performed a self-review of my code.
- [ ] :bookmark_tabs: I have commented my code, particularly in hard-to-understand areas.
- [ ] :bookmark: I have made corresponding changes to the documentation.
- [ ] :warning: My changes generate no new warnings.
- [ ] :monocle_face: I have added tests that prove my fix is effective or that my feature works.
- [ ] :white_check_mark: New and existing unit tests pass locally with my changes.
- [ ] :link: Any dependent changes have been merged and published in downstream modules.

## Required links:

- **Linear Issue**:
- **Testing Notebook** (Colab):
- **Code Documentation** (Confluence):
- **User Documentation** (Confluence):

## Contributors:
- Name 1
- Name 2

2024-04-18 13:46 UTC, jithintgeorge submitted a review, later dismissed

2024-04-19 08:27 UTC, gargimaheshwari requested changes
@praveenlyzr please make the following changes:
1. Delete `dist`, `build` and `lyzr.egg-info` folders
2. Merge `main` into this branch
3. Update `setup.py` to v0.1.36 (0.1.35 has already been published)
4. Rebuild
5. Commit and push changes

2024-04-25 08:18 UTC, gargimaheshwari requested changes
@praveenlyzr I can see that there are two conflicts

> This branch has conflicts that must be resolved
Use the [web editor](https://github.com/LyzrCore/lyzr/pull/41/conflicts) or the to resolve conflicts.
Conflicting files
lyzr.egg-info/PKG-INFO
setup.py

Please make changes per the steps in my comment here: https://github.com/LyzrCore/lyzr/pull/41#pullrequestreview-2010845499

2024-04-25 09:06 UTC, gargimaheshwari approved these changes

2024-04-25 09:07 UTC, jithintgeorge approved these changes

2024-04-25 09:08 UTC, merged